### ISSUE TITLE
Marshal/Unmarshal skips newline characters CR LF

### ISSUE THREAD

**Issue by galyanikolova** [eclipse-ee4j/jaxb-ri#1246]
Recently we discover that after marshal/unmarshal the result string is not identical with the original one and skips new lines (CR, LF or CRLF). 
There are very similar issues reported in the past ([#226](https://github.com/eclipse-ee4j/jaxb-ri/issues/226), [#449](https://github.com/eclipse-ee4j/jaxb-ri/issues/449), [#959](https://github.com/eclipse-ee4j/jaxb-ri/issues/959), [#1030](https://github.com/eclipse-ee4j/jaxb-ri/issues/1030)) for different versions and for some of them, it is marked as fixed. The interesting part is that in previous version that we used – 2.2.11, there was not such an issue, but in current – 2.3.0 there is a problem.

**Affected Versions**
**[2.3.0]**

**Comment by bravehorsie** [comment]
@galyanikolova There were some changes to new line escape handling in 2.3.0 and later.
Bugs in question were: 
https://bugs.openjdk.java.net/browse/JDK-8196491
https://bugs.openjdk.java.net/browse/JDK-8172297
https://bugs.openjdk.java.net/browse/JDK-8171195

The PR referenced is quite an old one. In order to not reintroduce any regression, lets nail down the problem first.

First, issue you are reporting is due to [XML parsers normalization](https://www.w3.org/TR/REC-xml/#sec-line-ends). It should relate only to escaping `\r` (carriage return), not the `\n` (line feed).

I have tested both 2.3.0 and 2.3.2 in most basic JAXB configuration and get no issues with CR/LF not being preserved after a JAXB marshall/unmarshall roundtrip.
https://github.com/bravehorsie/jaxb-newline-test

Please provide an example demonstrating the issue (ideally on last released version 2.3.2).

**Comment by lukasj** [comment]
works fine with 2.3.6/3+; reproducible in "old" version included in SE 8 b311
