### ISSUE TITLE
XJC: fails to process XSD files without systemId

### ISSUE THREAD

**Issue by raphw** [eclipse-ee4j/jaxb-ri#1502]
If an XSD contains a namespace import without specifying a *schemaLocation*, XJC fails with JAXP09020006 since version 2.3.0. Prior, to that version, such XSD files can be processed without any issues. This can be worked around by adding a class:

```java
package com.sun.tools.xjc;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;

import javax.xml.catalog.CatalogFeatures;
import javax.xml.catalog.CatalogManager;
import javax.xml.catalog.CatalogResolver;
import org.xml.sax.EntityResolver;

public class CatalogUtil {

    static EntityResolver getCatalog(EntityResolver entityResolver, File catalogFile, ArrayList<URI> catalogUrls) throws IOException {
        if (entityResolver != null) {
            return entityResolver;
        }
        CatalogResolver resolver = CatalogManager.catalogResolver(CatalogFeatures.builder().build(), catalogUrls.toArray(URI[]::new));
        return (publicId, systemId) -> resolver.resolveEntity(publicId, systemId == null ? "" : systemId);
    }
}
```

to shadow the bundled `CatalogUtil` where the null value is replaced by an empty string.

Ideally, this could also be fixed in version 2.3.3 which is still in heavy use. Right now it is for example impossible to use the *jaxb2-maven-plugin* on Java 11 with OASIS catalog files.

**Comment by lukasj** [comment]
Can you provide sample xsd for reproducing this, please? Thanks!

**Comment by raphw** [comment]
Given *simple.xsd*:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="simple:namespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="simple:namespace">
    <xsd:complexType name="Sample">
        <xsd:sequence>
            <xsd:element name="value" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>
```

and importing.xsd:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="importing:namespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="importing:namespace" xmlns:simple="simple:namespace">
    <xsd:import namespace="simple:namespace"/>
    <xsd:complexType name="Extended">
        <xsd:sequence>
            <xsd:element name="value" type="simple:Sample"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>
```

One should be able to specify the following catalog:

```xml
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <public publicId="simple:namespace" uri="simple.xsd"/>
</catalog>
```

which currently fails since the catalog is not considered during validation of *importing.xsd*.

**Comment by lukasj** [comment]
Reproduced, thanks. At first I was thinking the problem is that [SchemaConstraintChecker](https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/xjc/src/main/java/com/sun/tools/xjc/reader/xmlschema/parser/SchemaConstraintChecker.java#L61) hides [resolveResource](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/catalog/CatalogResolver.html#resolveResource(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)) method defined by `javax.xml.catalog.CatalogResolver` in JDK 11 for which `null` systemId may be valid input but an experiment led to NPE, which is strange.

When I read the javadoc for [LSResourceResolver.resolveResource](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/org/w3c/dom/ls/LSResourceResolver.html#resolveResource(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)) then `null` is valid value for `systemId` but when I read the javadoc for the same method in [CatalogResolver](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/catalog/CatalogResolver.html#resolveResource(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)), it wrt handling of `systemId` points to [resolveEntity method](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/catalog/CatalogResolver.html#resolveEntity(java.lang.String,java.lang.String)) and if I got it right, it disallows `null` (at least according to [JDK-8150187](https://bugs.openjdk.java.net/browse/JDK-8150187)) and that seems to me like the implementation of the contract defined by the LSResourceResolver interface is a bit broken. I think this is a bug in JDK.

...in any case, this should not be difficult to workaround

**Comment by lukasj** [comment]
hopefully fixed in master. Note that while there is a plan to provide v2.3.4 in the near future (and fix for this may be part of it), for using Java 11, I strongly recommend to switch over to 3.0.1 once its made available because it will have option to generate `javax` code (see #1475) and will be able to run properly - or at least better than 2.x - on JPMS. JAXB version 2.x contains packages split over few jars, so unless one wants do depend on its internal structure/modules, it won't run properly on JPMS.

**Comment by raphw** [comment]
Brilliant, thanks! And very good move to support the javax namespace again; this was an actual issue I anticipated. Thanks for the quick fix!
