### ISSUE TITLE
UnmarshallingContext - shouldErrorBeReported log level as condition

### ISSUE THREAD

**Issue by lucalas** [eclipse-ee4j/jaxb-ri#1520]
Hi everybody,
we are using your library for a long time and I'm here to ask you an explanation about a method inside of [UnmarshallingContext.java](https://github.com/eclipse-ee4j/jaxb-ri/blob/d0386f88a6f53972614dbb4a9953c164d8f4dc79/jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/v2/runtime/unmarshaller/UnmarshallingContext.java) class.

There is shouldErrorBeReported method:
``` java
    public boolean shouldErrorBeReported() throws SAXException {
        if (logger.isLoggable(Level.FINEST))
            return true;

        if (errorsCounter >= 0) {
            --errorsCounter;
            if (errorsCounter == 0) // it's possible to miss this because of concurrency. If required add synchronization here
                handleEvent(new ValidationEventImpl(ValidationEvent.WARNING, Messages.ERRORS_LIMIT_EXCEEDED.format(),
                        getLocator().getLocation(), null), true);
        }
        return errorsCounter >= 0;
    }
```

and I want to ask you if is there a specific reason to use `if (logger.isLoggable(Level.FINEST))` as a condition to managed reporting of the errors? Could be useful to have a configurable flag to managed this condition instead of log level?

**Comment by lukasj** [comment]
yes, the reason is explained in [the javadoc](https://github.com/eclipse-ee4j/jaxb-ri/blob/d0386f88a6f53972614dbb4a9953c164d8f4dc79/jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/v2/runtime/unmarshaller/UnmarshallingContext.java#L164) of the `errorsCounter` field:

> The variable introduced to avoid reporting n^10 similar errors.

Configurable flag is there too, see [JAXBRIContext](https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/api/JAXBRIContext.java#L533) (or [pre-Jakarta version](https://github.com/eclipse-ee4j/jaxb-ri/blob/EE8/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/api/JAXBRIContext.java#L538))
