### ISSUE TITLE
schemagen and xjc should add 'if-exists' to bindings when generating an episode file

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#829]
When schemagen or xjc generates an episode file (via the -episode command-line argument; or in the case of the schemagen ant task, the episode attribute), the resultant file should set the 'if-exists' attribute on the 2nd-level bindings element.

Rationale: When generating an episode file, you may be generating bindings for multiple namespaces at once (especially if you're using schemagen and adding the episode file to your META-INF section of a jar file). If you then try to consume that bindings file via xjc (as documented at [http://weblogs.java.net/blog/2006/09/05/separate-compilation-jaxb-ri-21](http://weblogs.java.net/blog/2006/09/05/separate-compilation-jaxb-ri-21)), it will fail if your input schema doesn't have references to all of the namespaces included in the episode file. At least, it will fail if you're using the Ant xjc task, I haven't tried from the command line.

However, if the bindings had 'if-exists' set on them, the xjc task would simply keep going (the code that checks for this attribute is in SCDBasedBindingSet::Target::apply).

Concise example:

Output is currently generated like this:

<bindings version="2.1" xmlns="http://java.sun.com/xml/ns/jaxb">
<bindings scd="x-schema::tns" xmlns:tns="http://example.com/SomeSampleNamespace/">
<schemaBindings map="false"/>
<bindings scd="tns:SampleElement">
<class ref="com.example.sample.SampleElement"/>
</bindings>
/**...**/
</bindings>
</bindings>

If it was instead this (note the if-exists on the bindings with scd attribute):

<bindings version="2.1" xmlns="http://java.sun.com/xml/ns/jaxb">
<bindings scd="x-schema::tns" xmlns:tns="http://example.com/SomeSampleNamespace/" if-exists="">
<schemaBindings map="false"/>
<bindings scd="tns:SampleElement">
<class ref="com.example.sample.SampleElement"/>
</bindings>
/**...**/
</bindings>
</bindings>

Then the xjc task would ignore any unused bindings when processing it with the -b or from a jar file's META-INF. I think this would be the desired action when using bindings generated as an episode file.
#### Affected Versions
[2.2.3u1]

**Comment by phax** [comment]
Well, it seems like this issue was resolved in a 2.3.0 version:
```xml
    <!--

This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
Any modifications to this file will be lost upon recompilation of the source schema. 
Generated on: 2021.05.02 at 06:39:11 PM CEST 

  -->
      
    <bindings xmlns:tns="http://www.w3.org/2009/xmldsig11#" if-exists="true" scd="x-schema::tns">
```

Unfortunately this is no longer the case in v4.0.1:

```xml
    <!--

This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
See https://eclipse-ee4j.github.io/jaxb-ri 
Any modifications to this file will be lost upon recompilation of the source schema. 
Generated on: 2022.12.06 at 08:06:11 PM CET
  -->
      
    <bindings xmlns:tns="http://www.w3.org/2009/xmldsig11#" scd="x-schema::tns">
```

So I guess, this is a new error for JAXB 4.0.x?

**Comment by getaceres** [comment]
It's been 12 years since this issue was open and still this option is not supported by XJC which makes automatic episode generation useless for many use cases. I also have a shared schema between many WSDLs but each one of them uses just a subset of the whole schema, which results in the awful `SCD "<whatever>" didnt match any schema component` and that's stupid. The xjb file has all the elements that the WSDL might need but it fails because the WSDL doesn't reference them all. 
The highsource plugin adds the "if-exist" option but it only supports JAXB 2 yet and we need JAXB 3 and 4 for Spring Boot 3 projects. Having such an option in the base xjc tool would be really really helpful.

**Comment by laurentschoelens** [comment]
Hi @getaceres (and @phax 😄 )

I just made a PR in jaxb-ri to end with `jaxb-maven-plugin` _hack_ which adds `if-exists` attributes by default in episode file, since it doesn't hurt anyone from many years now.

We are also working with Matt on JAXB3 support (which is just javax -> jakarta change) and then fastly move and release JAXB4 support plugin versions. This will come very soon, the hard part of the work were done in latest v2 releases.

Regards
